// Explicit synthetic fixtures for rehearsing motion. Never mixed with collected Reels.
import {VERSION} from './schema.mjs';
export function demo(){
 const examples=[
 ['question','curiosity','explanation','Por que algumas ideias ficam meses esquecidas nas suas anotações?','O próximo passo costuma ser vago demais. Anote uma coisa que você consiga terminar em dez minutos.','principle'],
 ['claim','contradiction','problem_solution','Uma lista de tarefas maior pode deixar seu dia menos produtivo.','Cada nova tarefa compete com a que realmente importa. Escolha um resultado antes de abrir sua caixa de entrada.','action'],
 ['instruction','mistake','steps','Pare de reescrever a mesma abertura dez vezes.','Escreva primeiro a parte útil. Depois explique para quem ela serve. Use isso para criar a abertura.','sequence'],
 ['story','story','story','Na semana passada, encontrei um caderno cheio de ideias inacabadas.','Uma delas tinha um próximo passo claro. Terminei essa primeiro. Isso me ajudou a planejar melhor as outras.','action'],
 ['claim','result','explanation','Um exemplo claro pode facilitar a explicação de uma ideia complicada.','Pegue uma tarefa conhecida e mostre exatamente o que mudou. Deixe o exemplo explicar uma parte.','action'],
 ['claim','recognition','opinion','Sabe quando você trabalha o dia todo e ainda sente que não concluiu nada?','Às vezes, você precisa definir melhor o que significa terminar. Escolha algo que realmente consiga concluir hoje.','action']
 ];
 const now=Date.now();const posts=Array.from({length:144},(_,i)=>{
  const e=examples[i%examples.length];const confidence=0.72+(i%23)/100;const label=v=>({value:v,confidence});const views=Math.round(2400*Math.pow(1.057,i%112)*(1+(i%3)*0.6));
  const segments=[{id:'s0',start:0,end:6,text:e[3],value:'hook',confidence},{id:'s1',start:6,end:17,text:e[4],value:i%2?'advice':'example',confidence},{id:'s2',start:17,end:23,text:'Comece com um exemplo que você possa usar hoje.',value:'payoff',confidence}];
  return {id:`rehearsal-${i}`,creator:'demo.creator',url:'',publishedAt:new Date(now-(20+i)*864e5).toISOString(),scrapedAt:new Date(now).toISOString(),caption:'Exemplo sintético para ensaio visual',likes:Math.round(views*(0.009+(i*13%70)/1000)),comments:i*3,views,plays:null,duration:23+(i%50),thumbnailUrl:`/demo-art/${i%12}.svg`,videoUrl:'',status:'complete',transcript:{text:segments.map(s=>s.text).join(' '),segments,source:'synthetic fixture'},analysis:{schemaVersion:VERSION,model:'synthetic fixture',labels:{topic:label(i%3?'habits':'marketing'),opening:label(e[0]),mechanism:label(e[1]),structure:label(e[2]),evidence:label(i%2?'reasoning':'example'),emotion:label(i%3?'aspiration':'relief'),specificity:label(e[5]),cta:label('none')},anatomy:segments,opening:e[3],inputTokens:null,costUsd:null,review:false,completedAt:new Date(now).toISOString()}};
 });return {id:'demo',creator:'demo.creator',status:'rehearsal',synthetic:true,posts,events:[],costs:{apify:null},elapsedMs:0,retries:0};
}
export function artwork(i){const colors=['#dccfb3','#94a795','#d07d61','#9bafbd','#c6b5aa','#ac9f7c'];const c=colors[i%6];return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 160"><rect width="120" height="160" fill="${c}"/><path d="M0 160 Q5 103 60 96 Q115 103 120 160" fill="#282d29"/><ellipse cx="60" cy="62" rx="28" ry="35" fill="#e4bd97"/><path d="M32 59 Q25 16 60 20 Q100 18 88 61 L78 41 Q56 51 38 40Z" fill="#34312c"/><path d="M45 63 h5 M71 63 h5" stroke="#30312b" stroke-width="3"/><path d="M52 80 Q60 84 68 79" stroke="#7d4a3b" fill="none"/><rect x="10" y="120" width="100" height="23" fill="#f7f1df"/><text x="60" y="135" font-family="sans-serif" font-size="9" text-anchor="middle" fill="#21241f">QUADRO DE DEMONSTRAÇÃO ${i+1}</text></svg>`;}
